Models/ErrorViewModel.cs
namespace ExemploAspNetMvc.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/UserModel.cs
namespace ExemploAspNetMvc.Controllers;

public class UserCreateDto
{
    public string Nome { get; set; }
    public string Email { get; set; }
    public string Senha { get; set; }
}

Controllers/CalculadoraController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ExemploAspNetMvc.Models;

namespace ExemploAspNetMvc.Controllers;

public class CalculadoraController : Controller 
{
    private readonly ILogger<CalculadoraController> _logger;

    public CalculadoraController(ILogger<CalculadoraController> logger)
    {
        _logger = logger;
    }

    public IActionResult Operacao()
    {
        return View();
    }

    public IActionResult OperacaoResultado([FromForm] double num1, [FromForm] double num2, [FromForm] string operacao) 
    {
        ViewBag.numero1 = num1;
        ViewBag.numero2 = num2;

        if(operacao == "Somar")
        {
            ViewBag.operacao = "soma";
            ViewBag.operador = "+";
            ViewBag.resultado = num1 + num2;
        }

        if(operacao == "Subtrair")
        {
            ViewBag.operacao = "subtração";
            ViewBag.operador = "-";
            ViewBag.resultado = num1 - num2;
        }

        if(operacao == "Multiplicar")
        {
            ViewBag.operacao = "multiplicação";
            ViewBag.operador = "x";
            ViewBag.resultado = num1 * num2;
        }

        if(operacao == "Dividir")
        {
            ViewBag.operacao = "divisão";
            ViewBag.operador = "+";
            ViewBag.resultado = num1 / num2;
        }

        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ExemploAspNetMvc.Models;

namespace ExemploAspNetMvc.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult PrimeiraAction() 
    {
        return View();
    }

    public string TesteQueryString([FromQuery] string q, [FromQuery] string nome)
    {
        return $"Chegou aqui {q} e {nome}";
    }

    // public string TesteFormData([FromForm] string nome, [FromForm] string email) 
    // {
    //     return $"Nome: {nome}, E-mail: {email}";
    // }

    public IActionResult Formulario()
    {
        return View();
    }

    public string TesteFormData([FromForm] UserCreateDto userCreateDto, [FromHeader] string x) 
    {
        return $"Nome: {userCreateDto.Nome}, E-mail: {userCreateDto.Email}, Senha: {userCreateDto.Senha}, x: {x}";
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Calculadora/Operacao.cshtml
@{
    ViewData["Title"] = "Calculadora Page";
}

<h1>Calculadora</h1>
<br><br>
<p>Utilize o formulário para realizar uma operação matemática</p>
<br><br>
<form id="form" action="OperacaoResultado" method="post">
    <label for="num1">Número 1</label>
    <input type="number" name="num1" id="num1">
    <label for="num2">Número 2</label>
    <input type="number" name="num2" id="num2">
    <label for="operacao">Operação</label>
    <select name="operacao" id="operacao">
        <option value="Somar">Somar</option>
        <option value="Subtrair">Subtrair</option>
        <option value="Multiplicar">Multiplicar</option>
        <option value="Dividir">Dividir</option>
    </select>
    <button type="submit">Calcular</button>
</form>

Views/Calculadora/OperacaoResultado.cshtml
@{
    ViewData["Title"] = "Calculadora Page Result";
}

<p>A @ViewBag.operacao de @ViewBag.numero1 @ViewBag.operador @ViewBag.numero2 é igual a @ViewBag.resultado</p>

Views/Home/Formulario.cshtml
@{
    ViewData["Title"] = "Primeiro Form";
}

<form id="form" action="TesteFormData" method="post">
    <label for="nome">Nome</label>
    <input type="text" name="nome" id="nome">
    <label for="email">Email</label>
    <input type="text" name="email" id="email">
    <label for="senha">Senha</label>
    <input type="text" name="senha" id="senha">
    <button type="submit">Enviar</button>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/PrimeiraAction.cshtml
@{
    ViewData["Title"] = "Primeira Action";
}

<div class="text-center">
    <h1>Primeira Action</h1>
</div>

Views/OperacoesMatematicas/Divisao.cshtml
@{
    ViewData["Title"] = "Divisão Page";
}

<h1>Operação Matemática Dividir</h1>
<br><br>
<p>Utilize o formulário abaixo para dividir dois números</p>
<br><br>
<form id="form" action="DivisaoResultado" method="post">
    <label for="num1">Número 1</label>
    <input type="number" name="num1" id="num1">
    <label for="num2">Número 2</label>
    <input type="number" name="num2" id="num2">
    <button type="submit">Dividir</button>
</form>

Views/OperacoesMatematicas/DivisaoResultado.cshtml
@{
    ViewData["Title"] = "Divisão Page Result";
}

<h1>Resultado da Divisão</h1>
<br><br>
<p> A divisão de @ViewBag.numero1 / @ViewBag.numero2 é igual a @ViewBag.resultado</p>

Views/OperacoesMatematicas/Multiplicacao.cshtml
@{
    ViewData["Title"] = "Multiplicação Page";
}

<h1>Operação Matemática Multiplicar</h1>
<br><br>
<p>Utilize o formulário abaixo para multiplicar dois números</p>
<br><br>
<form id="form" action="MultiplicacaoResultado" method="post">
    <label for="num1">Número 1</label>
    <input type="number" name="num1" id="num1">
    <label for="num2">Número 2</label>
    <input type="number" name="num2" id="num2">
    <button type="submit">Multiplicar</button>
</form>

Views/OperacoesMatematicas/MultiplicacaoResultado.cshtml
@{
    ViewData["Title"] = "Multiplicação Page Result";
}

<h1>Resultado da Multiplicação</h1>
<br><br>
<p> A multiplicação de @ViewBag.numero1 * @ViewBag.numero2 é igual a @ViewBag.resultado</p>

Views/OperacoesMatematicas/Soma.cshtml
@{
    ViewData["Title"] = "Soma Page";
}

<h1>Operação Matemática Somar</h1>
<br><br>
<p>Utilize o formulário abaixo para somar dois números</p>
<br><br>
<form id="form" action="SomaResultado" method="post">
    <label for="num1">Número 1</label>
    <input type="number" name="num1" id="num1">
    <label for="num2">Número 2</label>
    <input type="number" name="num2" id="num2">
    <button type="submit">Somar</button>
</form>

Views/OperacoesMatematicas/SomaResultado.cshtml
@{
    ViewData["Title"] = "Soma Page Result";
}

<h1>Resultado da Soma</h1>
<br><br>
<p> A soma de @ViewBag.numero1 + @ViewBag.numero2 é igual a @ViewBag.resultado</p>

Views/OperacoesMatematicas/Subtracao.cshtml
@{
    ViewData["Title"] = "Subtração Page";
}

<h1>Operação Matemática Subtrair</h1>
<br><br>
<p>Utilize o formulário abaixo para subtrair dois números</p>
<br><br>
<form id="form" action="SubtracaoResultado" method="post">
    <label for="num1">Número 1</label>
    <input type="number" name="num1" id="num1">
    <label for="num2">Número 2</label>
    <input type="number" name="num2" id="num2">
    <button type="submit">Subtrair</button>
</form>

Views/OperacoesMatematicas/SubtracaoResultado.cshtml
@{
    ViewData["Title"] = "Subtração Page Result";
}

<h1>Resultado da Subtração</h1>
<br><br>
<p> A subtração de @ViewBag.numero1 - @ViewBag.numero2 é igual a @ViewBag.resultado</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExemploAspNetMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExemploAspNetMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExemploAspNetMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="PrimeiraAction">Primeira Action</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OperacoesMatematicas" asp-action="Soma">Soma</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OperacoesMatematicas" asp-action="Subtracao">Subtração</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OperacoesMatematicas" asp-action="Multiplicacao">Multiplicação</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OperacoesMatematicas" asp-action="Divisao">Divisão</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Operacao">Calculadora</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ExemploAspNetMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>